apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-boot.fullname" . }}-cfg
  labels:
    {{- include "spring-boot.labels" . | nindent 4 }}
data:
  application.yaml: |
    spring:
      threads:
        virtual:
          enabled: true
    springdoc:
      swagger-ui:
        use-root-path: true
